### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by mingtang1079** [dhhAndroid/RxLife#1]
Caused by: java.lang.RuntimeException: Stub! 
        at com.appbaselib.rxlife.ActivityThread.currentApplication(ActivityThread.java:12
请问下大佬这个是啥问题，我把源码放到自己的项目出现这个问题，是application获取不到。。

**Comment by dhh-io** [comment]
你试试用Gradle依赖使用，以为项目里有一个模块是 AndroidStub 模块，是 Hook ActivityThread的，用来获取程序的Application的，rxlife1和rxlife2依赖这个AndroidStub模块都是以compileOnly 方式依赖的，你应该是该了我依赖的方式。

**Comment by dhh-io** [comment]
你看下是不是我说的原因导致的，改了依赖方式，或者你直接使用gradle直接依赖使用吧，不用依赖源码

**Comment by mingtang1079** [comment]
> 你看下是不是我说的原因导致的，改了依赖方式，或者你直接使用gradle直接依赖使用吧，不用依赖源码

是的。。。就是想看看大佬的源码，所以没用依赖

**Comment by mingtang1079** [comment]
> 你试试用Gradle依赖使用，以为项目里有一个模块是 AndroidStub 模块，是 Hook ActivityThread的，用来获取程序的Application的，rxlife1和rxlife2依赖这个AndroidStub模块都是以compileOnly 方式依赖的，你应该是该了我依赖的方式。

原来这样也可以hook啊，大佬 ，这么hook的原理是啥呢

**Comment by dhh-io** [comment]
现在崩溃的问题解决了吗 ？这种hook的方式，是避免反射调用系统隐藏API，性能更高，方式更加优雅。原理就是绕过编译器检测，编译期用的我写的相同包名的相同类，就是抄系统源码，但是不用有具体实现，然后以compileOnly 的方式只在编译期依赖，这样在运行期runtime时，代码走的是系统源码。

**Comment by mingtang1079** [comment]
> 现在崩溃的问题解决了吗 ？这种hook的方式，是避免反射调用系统隐藏API，性能更高，方式更加优雅。原理就是绕过编译器检测，编译期用的我写的相同包名的相同类，就是抄系统源码，但是不用有具体实现，然后以compileOnly 的方式只在编译期依赖，这样在运行期runtime时，代码走的是系统源码。

解决了，大佬厉害了，同时学习了！

**Comment by dhh-io** [comment]
基本上系统的API都可以这样hook，这个项目里需要获取一下程序的Application做一下初始化，通过这种hook方式，可以自动获取Application，自动初始化，不需要用户再初始化。这种方式在写SDK 的时候，十分好用。

**Comment by mingtang1079** [comment]
> 基本上系统的API都可以这样hook，这个项目里需要获取一下程序的Application做一下初始化，通过这种hook方式，可以自动获取Application，自动初始化，不需要用户再初始化。这种方式在写SDK 的时候，十分好用。

好的，感谢大佬，我不知道还可以这样用。。。
